name: erdtree
slug: erdtree
version: 3.1.2
description: multi-threaded file-tree visualizer and disk usage analyzer
homepage: https://github.com/solidiquis/erdtree
license: MIT
maintainer: solidiquis
dependencies:
  - rustup
