name: bubblewrap
slug: bubblewrap
version: 0.11.0
description: an unprivileged sandboxing tool for running applications in a restricted environment
homepage: https://github.com/containers/bubblewrap
license: LGPL-2.1
maintainer: containers project
dependencies:
  - gcc
  - meson
  - ninja
