name: valgrind
slug: valgrind
version: 3.24.0
description: an instrumentation framework for building dynamic analysis tools, memory error detector
homepage: https://valgrind.org
license: GPL-2.0
maintainer: valgrind
dependencies:
  - autoconf
  - make
