name: fd
slug: fd
version: 10.2.0
description: simple, fast, and user-friendly alternative to find
homepage: https://github.com/sharkdp/fd
license: MIT OR Apache-2.0
maintainer: sharkdp
dependencies:
  - rustup
