name: k3s
slug: k3s
version: 1.31.2
description: a lightweight, certified Kubernetes distribution built for edge and IoT
homepage: https://github.com/k3s-io/k3s
license: Apache-2.0
maintainer: Rancher (SUSE)
dependencies:
  - go
