name: feh
slug: feh
version: 3.10.3
description: fast, lightweight image viewer for X using imlib2
homepage: https://github.com/derf/feh
license: MIT
maintainer: Birte Kristina Friesel
dependencies:
  - gcc
  - make
