name: ansible
slug: ansible
version: 11.2.0
description: a radically simple IT automation and configuration management platform
homepage: https://github.com/ansible/ansible
license: GPL-3.0
maintainer: Red Hat, Inc.
dependencies:
