name: httpx
slug: httpx
version: 1.12.0
description: fast and multi-purpose HTTP toolkit
homepage: https://github.com/projectdiscovery/httpx
license: MIT
maintainer: ProjectDiscovery
dependencies:
  - go
