name: impacket
slug: impacket
version: 0.12.0
description: collection of Python classes for working with network protocols
homepage: https://github.com/fortra/impacket
license: Apache-1.1
maintainer: Fortra
dependencies:
  - python
