name: yazi
slug: yazi
version: 0.4.0
description: blazing fast terminal file manager written in rust, based on async i/o
homepage: https://github.com/sxyazi/yazi
license: MIT
maintainer: sxyazi
dependencies:
  - rustup
