name: restic
slug: restic
version: 0.17.1
description: a fast, secure, efficient backup program
homepage: https://github.com/restic/restic
license: BSD-2-Clause
maintainer: restic
dependencies:
  - go
