name: trippy
slug: trippy
version: 0.13.0
description: a network diagnostic tool combining traceroute and ping
homepage: https://github.com/fujiapple852/trippy
license: Apache-2.0
maintainer: fujiapple852
dependencies:
  - rustup
